1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

NumPy is a library for numerical computing in Python. It provides:

Efficient array operations: N-dimensional arrays for fast, memory-efficient data manipulation.

Mathematical functions: Vectorized operations, reducing the need for loops.

Broadcasting: Operations on arrays of different shapes.
Linear algebra, statistics, random generation: Built-in functions for complex computations.
It enhances Python's capabilities by offering optimized performance, reducing execution time, and simplifying numerical tasks.

2.  Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

np.mean(): Calculates the arithmetic mean of an array. It returns the sum of the elements divided by the number of elements.

np.average(): Calculates the weighted average, allowing you to specify weights for the elements.

Use case:
Use np.mean() for a simple average.
Use np.average() when you need to compute a weighted average with specified weights.

3.  Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

Reversing a NumPy array:

1D Array: Use slicing to reverse.

import numpy as np
arr1d = np.array([1, 2, 3, 4, 5])
reversed_arr1d = arr1d[::-1]
print(reversed_arr1d)  # Output: [5 4 3 2 1]
2D Array: Reverse along a specific axis using slicing.

Along rows (axis 0):
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = arr2d[::-1, :]
print(reversed_rows)  # Output: [[7 8 9] [4 5 6] [1 2 3]]

Along columns (axis 1):
reversed_cols = arr2d[:, ::-1]
print(reversed_cols)  # Output: [[3 2 1] [6 5 4] [9 8 7]]

4.How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

use the .dtype attribute to determine the data type of elements in a NumPy array.
import numpy as np
arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: int64 (or similar depending on system)

Importance of Data Types:

Memory Management: Smaller data types (e.g., np.int8) use less memory, enabling efficient storage.

Performance: Operations on arrays with appropriate data types are faster due to optimized handling in NumPy.

5.Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

ndarrays (N-dimensional arrays) in NumPy are multi-dimensional, homogeneous arrays used for storing large datasets.

Key Features:
Homogeneous: All elements must have the same data type.
Multidimensional: Can have multiple dimensions (1D, 2D, 3D, etc.).
Efficient: Optimized for fast operations and low memory consumption.
Vectorized operations: Enables element-wise operations without loops.

Difference from Python Lists:

Data Type: Lists can store mixed data types, whereas ndarrays are homogeneous.

Memory and Performance: ndarrays are more memory-efficient and faster for numerical operations.

Operations: NumPy arrays support element-wise operations, unlike Python lists.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

performance Benefits of NumPy Arrays over Python Lists:

Memory Efficiency: NumPy arrays use a contiguous block of memory, while Python lists store pointers to objects, making NumPy arrays more memory-efficient.

Faster Computations: NumPy arrays support vectorized operations, allowing element-wise calculations without loops, which is significantly faster than iterating over Python lists.

Optimized for Numerical Operations: NumPy is implemented in C, offering high-performance functions for large-scale numerical tasks, while Python lists are slower for numerical computation.

Lower Overhead: NumPy arrays handle large datasets with minimal overhead, whereas Python lists involve higher overhead due to dynamic typing and object storage.

7.Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

np.vstack(): Stacks arrays vertically (row-wise).
np.hstack(): Stacks arrays horizontally (column-wise).

Examples:
np.vstack() (vertical stacking):

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result_vstack = np.vstack((arr1, arr2))
print(result_vstack)
# Output:
# [[1 2 3]
#  [4 5 6]]

np.hstack() (horizontal stacking):

result_hstack = np.hstack((arr1, arr2))
print(result_hstack)
# Output:
# [1 2 3 4 5 6]

8.Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.


np.fliplr(): Flips the array left to right (horizontal flip).

Affects each row, reversing the order of elements in each row.

Example:
arr = np.array([[1, 2, 3], [4, 5, 6]])
result_fliplr = np.fliplr(arr)
print(result_fliplr)
# Output:
# [[3 2 1]
#  [6 5 4]]
np.flipud(): Flips the array upside down (vertical flip).

Affects the rows, reversing the order of rows in the array.

Example:

result_flipud = np.flipud(arr)
print(result_flipud)
# Output:
# [[4 5 6]
#  [1 2 3]]

9.Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The np.array_split() method splits an array into multiple sub-arrays. It can split an array into a specified number of equal (or nearly equal) parts along a given axis.

Functionality:
Syntax: np.array_split(arr, indices_or_sections, axis=0)
arr: The array to split.
indices_or_sections: Number of splits or an array of indices to split at.
axis: Axis along which to split (default is 0).

Handling Uneven Splits:
If the array cannot be evenly divided, np.array_split() distributes the elements as evenly as possible, with the remainder elements added to the first few sub-arrays.

Example:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split into 4 parts
result = np.array_split(arr, 4)
print(result)
# Output: [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8, 9])]

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Vectorization:

Vectorization refers to performing element-wise operations on entire arrays without explicit loops.

NumPy leverages C-level optimizations to apply operations to entire arrays, making them faster than traditional Python loops.

Example:
import numpy as np
arr = np.array([1, 2, 3])
result = arr * 2  # Element-wise multiplication
print(result)  # Output: [2 4 6]

Broadcasting:
Broadcasting allows NumPy to perform operations on arrays of different shapes by "stretching" the smaller array across the larger one.
It eliminates the need for manually reshaping arrays for element-wise operations.

Example:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10])
result = arr1 + arr2  # Broadcasting arr2 to match arr1's shape
print(result)  # Output: [11 12 13]

Efficiency:
Vectorization eliminates the need for explicit loops, speeding up operations.
Broadcasting reduces memory usage and simplifies array manipulation, avoiding unnecessary array reshaping.
Together, they enable efficient, fast, and memory-conserving operations on large datasets.

                            Pratical Questions

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.


In [1]:
import numpy as np

arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(arr)

transposed_arr = arr.T
print("\nTransposed Array:")
print(transposed_arr)

Original Array:
[[46 39 83]
 [81 43 47]
 [32 21 83]]

Transposed Array:
[[46 81 32]
 [39 43 21]
 [83 47 83]]


2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [2]:
import numpy as np

arr = np.arange(10)
print("Original 1D Array:")
print(arr)

arr_2x5 = arr.reshape(2, 5)
print("\nReshaped into 2x5 Array:")
print(arr_2x5)

arr_5x2 = arr.reshape(5, 2)
print("\nReshaped into 5x2 Array:")
print(arr_5x2)

Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [3]:
import numpy as np
arr = np.random.random((4, 4))
print("Original 4x4 Array:")
print(arr)

arr_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("\nArray with Zero Border (6x6):")
print(arr_with_border)

Original 4x4 Array:
[[0.80192943 0.55254876 0.25403215 0.63246042]
 [0.45406336 0.6014521  0.14655288 0.58865177]
 [0.84083816 0.27569629 0.31637154 0.84403182]
 [0.54909901 0.08035277 0.60036305 0.51802831]]

Array with Zero Border (6x6):
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.80192943 0.55254876 0.25403215 0.63246042 0.        ]
 [0.         0.45406336 0.6014521  0.14655288 0.58865177 0.        ]
 [0.         0.84083816 0.27569629 0.31637154 0.84403182 0.        ]
 [0.         0.54909901 0.08035277 0.60036305 0.51802831 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [4]:
import numpy as np
arr = np.arange(10, 61, 5)
print(arr)

[10 15 20 25 30 35 40 45 50 55 60]


5.  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element

In [5]:
import numpy as np
arr = np.array(['python', 'numpy', 'pandas'])

uppercase_arr = np.char.upper(arr)
lowercase_arr = np.char.lower(arr)
titlecase_arr = np.char.title(arr)

print("Uppercase:", uppercase_arr)
print("Lowercase:", lowercase_arr)
print("Titlecase:", titlecase_arr)

Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Titlecase: ['Python' 'Numpy' 'Pandas']


6.  Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [6]:
import numpy as np
arr = np.array(['python', 'numpy', 'pandas'])
spaced_arr = np.char.join(' ', arr)

print(spaced_arr)

['p y t h o n' 'n u m p y' 'p a n d a s']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [7]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [8]:
import numpy as np
identity_matrix = np.eye(5)

diagonal_elements = np.diagonal(identity_matrix)

print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)

Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array

In [9]:
import numpy as np
arr = np.random.randint(0, 1001, size=100)

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

primes = [num for num in arr if is_prime(num)]

print("Array:", arr)
print("Prime Numbers:", primes)

Array: [ 812   26  305   45  486  929  203  536  597  644  573  927  563  834
  939  962  238 1000  493  560  214  566  100  973  408  543  152  172
   33  862  210  686  498  578  762    6  526  370  554  191  964  101
  848  107  499  751  344  331  441  712  286  918   95  464  434  390
  746  688    7  491  600  264  842  265  137  511  363  901  624  262
  421  851  454  350  340  934   76  962  251   14  595  151  242  619
  941  465  121   67  828  252   64  779   63  815  432  941  255  488
  723  301]
Prime Numbers: [np.int32(929), np.int32(563), np.int32(191), np.int32(101), np.int32(107), np.int32(499), np.int32(751), np.int32(331), np.int32(7), np.int32(491), np.int32(137), np.int32(421), np.int32(251), np.int32(151), np.int32(619), np.int32(941), np.int32(67), np.int32(941)]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [13]:
import numpy as np
temperatures = np.random.randint(0, 35, size=28)

weekly_temperatures = temperatures.reshape(4, 7)

weekly_averages = weekly_temperatures.mean(axis=1)

print("Daily Temperatures:", temperatures)
print("Weekly Temperatures:\n", weekly_temperatures)
print("Weekly Averages:", weekly_averages)

Daily Temperatures: [ 2 23 23 11 26 28 32  0 25 17 17 13 27 12  4 20 25 30 16 31 11 19 31 17
  5 31  7 23]
Weekly Temperatures:
 [[ 2 23 23 11 26 28 32]
 [ 0 25 17 17 13 27 12]
 [ 4 20 25 30 16 31 11]
 [19 31 17  5 31  7 23]]
Weekly Averages: [20.71428571 15.85714286 19.57142857 19.        ]
